security:
  enable_authenticator_manager: true
  providers:
    entity_provider:
      id: App\Security\UserSecurityProvider

  firewalls:
    core:
      pattern: ^/
      guard:
        authenticators:
          - App\Security\TokenAuthenticator

  access_decision_manager:
    service: App\Security\AccessDecision
